#!/usr/bin/env bash
# 4 bad luck, 8 is your chance

var=1

while [ $var -le 20 ]
do
	echo $var

	case $var in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	var=$(( var + 1 ))
done
